# Generated by Django 5.2.7 on 2025-11-03 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Număr înmatriculare",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="make",
            field=models.CharField(max_length=100, verbose_name="Marcă"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(
                blank=True, max_length=17, null=True, verbose_name="Serie șasiu (VIN)"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(default=2020, verbose_name="An fabricație"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("owner", "license_plate")},
        ),
    ]
