# Generated by Django 5.2.7 on 2025-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_license_plate_vehicle_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="current_odometer",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Actualizează acest câmp periodic pentru a primi alerte de mentenanță.",
                verbose_name="Kilometraj Actual (km)",
            ),
        ),
    ]
