# Generated by Django 5.2.7 on 2025-11-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("odometer_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("OIL", "Oil change"),
                            ("FLT", "Filters"),
                            ("BRK", "Brakes"),
                            ("GEN", "General"),
                        ],
                        max_length=3,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
