# Generated by Django 5.2.7 on 2025-11-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        ("vehicles", "0002_vehicle_license_plate_vehicle_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data operațiunii")),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        help_text="Kilometrajul la momentul operațiunii",
                        verbose_name="Kilometraj (km)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Cost (RON)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        help_text="Ex: Schimb ulei și filtru aer, Plăcuțe frână față",
                        verbose_name="Descriere / Notițe",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="maintenance_attachments/",
                        verbose_name="Atașament (Factură)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="vehicles.vehicle",
                        verbose_name="Vehicul",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-odometer"],
            },
        ),
        migrations.DeleteModel(
            name="MaintenanceRecord",
        ),
    ]
