# Generated by Django 5.2.7 on 2025-11-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_maintenance_delete_maintenancerecord"),
        ("vehicles", "0003_vehicle_current_odometer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Ex: Schimb ulei și filtru, Schimb distribuție",
                        max_length=200,
                        verbose_name="Descriere Operațiune",
                    ),
                ),
                (
                    "km_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ex: 10000",
                        null=True,
                        verbose_name="Interval Kilometri (km)",
                    ),
                ),
                (
                    "months_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ex: 12",
                        null=True,
                        verbose_name="Interval Timp (luni)",
                    ),
                ),
                ("last_performed_date", models.DateField(verbose_name="Data ultimei operațiuni")),
                (
                    "last_performed_odometer",
                    models.PositiveIntegerField(verbose_name="Kilometrajul la ultima operațiune"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_alerts",
                        to="vehicles.vehicle",
                        verbose_name="Vehicul",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_performed_date"],
            },
        ),
    ]
