# Generated by Django 5.2.7 on 2025-11-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("RCA", "RCA"), ("ITP", "ITP"), ("ROV", "Rovinieta")], max_length=3
                    ),
                ),
                ("expires_on", models.DateField()),
                ("file", models.FileField(blank=True, upload_to="docs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_on"],
            },
        ),
    ]
