# Generated by Django 5.2.7 on 2025-11-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("vehicles", "0002_vehicle_license_plate_vehicle_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["expiry_date"]},
        ),
        migrations.RemoveField(
            model_name="document",
            name="doc_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="expires_on",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="document_attachments/",
                verbose_name="Atașament (PDF/Poză)",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RCA", "Asigurare RCA"),
                    ("ITP", "Inspecție Tehnică Periodică"),
                    ("ROVINIETA", "Rovinietă"),
                    ("CASCO", "Asigurare CASCO"),
                    ("OTHER", "Alt Document"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Tip Document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data expirării"),
        ),
        migrations.AddField(
            model_name="document",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Data emiterii"),
        ),
        migrations.AddField(
            model_name="document",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notițe"),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="vehicles.vehicle",
                verbose_name="Vehicul",
            ),
        ),
    ]
